# https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863
name: Create new release from pushed tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Build, Test, and Upload Builds (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Set VERSION variable from tag
        if: ${{ contains(github.ref, 'refs/tags') }}
        shell: bash
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
      - name: Print VERSION variable for debugging
        shell: bash
        run: echo "$VERSION"
        
      - name: Publish for Linux x64
        if: matrix.os == 'ubuntu-latest'
        run: dotnet publish -c Release -r linux-x64 --self-contained Refresher /p:Version=${VERSION}

      - name: Publish for Windows x64
        if: matrix.os == 'windows-latest'
        shell: bash
        run: dotnet publish -c Release -r win-x64 --self-contained Refresher //p:Version=${VERSION}

      - name: Publish for macOS x64
        if: matrix.os == 'macos-latest'
        shell: bash
        run: dotnet publish -c Release -r osx-x64 --self-contained Refresher /p:Version=${VERSION}
  
      - name: Publish for macOS ARM64
        if: matrix.os == 'macos-latest'
        shell: bash
        run: dotnet publish -c Release -r osx-arm64 --self-contained Refresher /p:Version=${VERSION}
      
      - name: Remove duplicate .app for macOS x64
        if: matrix.os == 'macos-latest'
        shell: bash
        working-directory: Refresher/bin/Release/net8.0/osx-x64/publish/
        run: rm -rfv ./*.app/Contents/MacOS/*.app && codesign -fs - --deep *.app
  
      - name: Remove duplicate .app for macOS ARM64
        if: matrix.os == 'macos-latest'
        shell: bash
        working-directory: Refresher/bin/Release/net8.0/osx-arm64/publish/
        run: rm -rfv ./*.app/Contents/MacOS/*.app && codesign -fs - --deep *.app
        
      # We need to tarball our macOS and Linux builds, since the ZIP files created by upload-artifact do not retain extended unix file permissions, 
      # which means the executable bit is lost, which is un-ideal for end users, who will hit weird errors (especially relating to code signing on macOS)
      - name: 'Tar macOS x64 build'
        if: matrix.os == 'macos-latest'
        working-directory: Refresher/bin/Release/net8.0/osx-x64/publish/
        run: tar -cvf ../../../../../../Refresher-x64.tar *.app
      - name: 'Tar macOS ARM64 build'
        if: matrix.os == 'macos-latest'
        working-directory: Refresher/bin/Release/net8.0/osx-arm64/publish/
        run: tar -cvf ../../../../../../Refresher-arm64.tar *.app 
      - name: 'Tar Linux x64'
        if: matrix.os == 'ubuntu-latest'
        working-directory: Refresher/bin/Release/net8.0/linux-x64/publish/
        run: tar -cvf ../../../../../../Refresher.tar * 

      - name: Upload Linux x64 build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3.1.3
        with:
            name: "refresher-linux-x64"
            path: "Refresher.tar"
            if-no-files-found: error
            retention-days: 1

      - name: Upload Windows x64 build
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3.1.3
        with:
            name: "refresher-win-x64"
            path: "Refresher/bin/Release/net8.0-windows/win-x64/publish/"
            if-no-files-found: error
            retention-days: 1

      - name: Upload macOS x64 build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3.1.1
        with:
            name: "refresher-macos-x64"
            path: "Refresher-x64.tar"
            if-no-files-found: error
            retention-days: 30
  
      - name: Upload macOS ARM64 build
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3.1.1
        with:
            name: "refresher-macos-arm64"
            path: "Refresher-arm64.tar"
            if-no-files-found: error
            retention-days: 1
  release:
    name: Release Built Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: src

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3.0.2

      - name: Create zip files
        run: |
            cd ${{steps.download.outputs.download-path}}/refresher-win-x64
            zip -r "${{steps.download.outputs.download-path}}/refresher-win-x64.zip" .
            
            cd ${{steps.download.outputs.download-path}}/refresher-linux-x64
            zip -r "${{steps.download.outputs.download-path}}/refresher-linux-x64.zip" .

            cd ${{steps.download.outputs.download-path}}/refresher-macos-x64
            zip -r "${{steps.download.outputs.download-path}}/refresher-macos-x64.zip" .

            cd ${{steps.download.outputs.download-path}}/refresher-macos-arm64
            zip -r "${{steps.download.outputs.download-path}}/refresher-macos-arm64.zip" .
        
      - uses: ncipollo/release-action@v1.14.0
        name: "Create release"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          generateReleaseNotes: true
          bodyFile: "RELEASE_NOTES.md"
          artifacts: |
            *.zip